set_property SRC_FILE_INFO {cfile:c:/vivadocodes/vedicdivide/project_1/project_1.srcs/constrs_1/new/timing_constraints.xdc rfile:../../../project_1.srcs/constrs_1/new/timing_constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 5.000 -name clk -waveform {0.000 2.500} [get_ports clk]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -min 0.500 [get_ports {dividend[*] divisor[*] valid_in rst_n}]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk -max 1.000 [get_ports {dividend[*] divisor[*] valid_in rst_n}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk -min 0.500 [get_ports {quotient[*] remainder[*] valid_out div_by_zero done}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk -max 1.000 [get_ports {quotient[*] remainder[*] valid_out div_by_zero done}]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_ports rst_n] -to [all_registers]
